# Generated by Django 4.1.1 on 2026-02-23 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('subscription_id', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('balance', models.FloatField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('overdue', 'Overdue'), ('paid', 'Paid')], max_length=20)),
                ('committee_specific_name', models.CharField(max_length=255)),
                ('fees', models.FloatField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.contact')),
                ('subscription_id_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.subscriptions')),
            ],
        ),
    ]
