# Generated by Django 4.1.1 on 2026-02-23 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=255, unique=True)),
                ('customer_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('future', 'Future'), ('live', 'Live'), ('expired', 'Expired')], max_length=20)),
                ('activated_at', models.DateField()),
                ('expires_at', models.DateField()),
                ('amount', models.FloatField()),
                ('addon', models.FloatField(default=0)),
                ('committee_specific_name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.contact')),
            ],
            options={
                'verbose_name_plural': 'Subscriptions',
            },
        ),
    ]
